services:
    tailscale:
        container_name: tailscaled
        ports:
            - 5252:5252
        volumes:
            - /var/lib:/var/lib
            - /dev/net/tun:/dev/net/tun
        network_mode: host
        cap_add:
            - NET_ADMIN
            - NET_RAW
        environment:
            - TS_AUTHKEY=tskey-auth-ab1CDE2CNTRL-0123456789abcdef
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_EXTRA_ARGS=--webclient
        image: tailscale/tailscale
