lzc-sdk-version: "0.1"
name: Tailscale
package: cloud.lazycat.app.tailscale
version: 1.84.0
description: 将您的设备和用户连接到您专属的安全虚拟专用网络。
homepage: https://tailscale.com
author: tailscale
application:
  subdomain: tailscale
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://host.lzcapp:59527

services:
  tailscale:
    container_name: tailscale
    image: registry.lazycat.cloud/czyt/tailscale/tailscale:c95ca3f07d1ab24e
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-routes --advertise-exit-node --accept-dns=true 
      - TS_USERSPACE=false
    entrypoint: ""
    command: /lzcapp/pkg/content/run.sh
    binds:
      - /lzcapp/var/data:/var/lib
    network_mode: host
    net_admin: true
    healthcheck:
      test:
        - CMD-SHELL
        - tailscale status --peers=false --json | grep -q 'Online.*true'
      start_period: 90s

ext_config:
  remove_this_request_headers:
    - origin
